version: '3.1'

services:
  db:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
  app:
    build: .
    command: bash -c " ./wait-for-postgres.sh db && python app.py"
    depends_on:
      - db
